### ISSUE TITLE
Any plans to add iOS support? 

### ISSUE THREAD

**Issue by DaveLomber** [mikakrooswijk/cordova-mongodb-storage#1]
Any plans to add iOS support?

**Comment by mikakrooswijk** [comment]
I plan to, but right now i don't have the Swift skill to do so. As soon as i have time to learn some Swift i will add it.

**Comment by DaveLomber** [comment]
@mikakrooswijk 
👍

**Comment by mikakrooswijk** [comment]
The develop branch now has support for iOS. It's just the same basic functions as in the Android version for now, more will come in the future tho. I have to do some further testing to make sure everything is working as it should be and that the iOS version behaves the same as the Android version.

**Comment by mikakrooswijk** [comment]
iOS support is now on NPM, so i'm closing this issue.
