### ISSUE TITLE
It is not possible to install this plugin

### ISSUE THREAD

**Issue by alekxeyuk** [mikakrooswijk/cordova-mongodb-storage#11]
**Describe the bug**
I can not install this plugin 'cause it does not have www folder with js file in it.

**To Reproduce**
1. Try to install it on windows 10

**Expected behavior**
Installed and working plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/9300326/61858042-a71ff780-af08-11e9-8e08-9db39fd61423.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by SitkaCharley** [comment]
Same problem here. Cordova 8.1.1

**Comment by mikakrooswijk** [comment]
This problem should be fix now so i'm closing this issue. If there is still a problem with installing this plugin please let me know.
